GET http://localhost:4000/video?category

###
PUT http://localhost:4000/video/like/617a18f4a5722d2788d25835
Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjkzOGYwN2FiMDlmYzBiMjI2ZjYxMSIsImlhdCI6MTYzNTQ3NjA3Nn0.daYZKa7PZ8n832A-UAGqmwqB4gNA9Q0lZXRp-Mvg6dU

###
PUT http://localhost:4000/video/dislike/617a18f4a5722d2788d25835
Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjkzOGYwN2FiMDlmYzBiMjI2ZjYxMSIsImlhdCI6MTYzNDMwNDExNn0.WZAyZs9vA6YBLcva7vaMbuoxOezbduF6nbjfohax4aU

###
GET http://localhost:4000/video/categories

###
GET http://localhost:4000/video/aJOTlE1K90k

###
POST http://localhost:4000/video
Content-Type: application/json
Token: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjkzOGYwN2FiMDlmYzBiMjI2ZjYxMSIsImlhdCI6MTYzNDMwNDExNn0.WZAyZs9vA6YBLcva7vaMbuoxOezbduF6nbjfohax4aU

{
  "title": "K'NAAN - Wavin' Flag (Coca-Cola Celebration Mix)",
  "videoId": "V2a-sl4l3_4",
  "category": "acoustic"
  # "video": "https://www.youtube.com/watch?v=vKPm8tQ1izo",
  # "thumbnail": "https://i.ytimg.com/vi/aJOTlE1K90k/sddefault.jpg",
}

###
POST http://localhost:4000/video
Content-Type: application/json
Token: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjk4YmY5N2M1NjVkZjVhMTU0MTVkOSIsImlhdCI6MTYzNDMwNzA3NH0.p6XNqg5YKWkVUE532xiZ6tZ2X3Xjva312THM1Y0HJt4

{
  "title": "The Kid LAROI, Justin Bieber - Stay DRUM | COVER By SUBIN",
  "videoId": "EsjwTK822IU",
  "category": "music"
  # "video": "https://www.youtube.com/watch?v=vKPm8tQ1izo",
  # "thumbnail": "https://i.ytimg.com/vi/aJOTlE1K90k/sddefault.jpg",
}

###
DELETE  http://localhost:4000/video/6177ce300c21a39c3f425292
Content-Type: application/json
Token: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjkzOGYwN2FiMDlmYzBiMjI2ZjYxMSIsImlhdCI6MTYzNDMwNDExNn0.WZAyZs9vA6YBLcva7vaMbuoxOezbduF6nbjfohax4aU

###
DELETE  http://localhost:4000/video/delete-all
Token: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjkzOGYwN2FiMDlmYzBiMjI2ZjYxMSIsImlhdCI6MTYzNDMwNDExNn0.WZAyZs9vA6YBLcva7vaMbuoxOezbduF6nbjfohax4aU

