GET http://localhost:4000/video?category=music
###
GET http://localhost:4000/video/categories
###

GET http://localhost:4000/video/aJOTlE1K90k

###
POST http://localhost:4000/video
Content-Type: application/json
Token: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjkzOGYwN2FiMDlmYzBiMjI2ZjYxMSIsImlhdCI6MTYzNDMwNDExNn0.WZAyZs9vA6YBLcva7vaMbuoxOezbduF6nbjfohax4aU

{
  "title": "K'NAAN - Wavin' Flag (Coca-Cola Celebration Mix)",
  "videoId": "kTJczUoc26U",
  "category": "acoustic"
  # "video": "https://www.youtube.com/watch?v=vKPm8tQ1izo",
  # "thumbnail": "https://i.ytimg.com/vi/aJOTlE1K90k/sddefault.jpg",
}

###
POST http://localhost:4000/video
Content-Type: application/json
Token: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjk4YmY5N2M1NjVkZjVhMTU0MTVkOSIsImlhdCI6MTYzNDMwNzA3NH0.p6XNqg5YKWkVUE532xiZ6tZ2X3Xjva312THM1Y0HJt4

{
  "title": "The Kid LAROI, Justin Bieber - Stay DRUM | COVER By SUBIN",
  "videoId": "EsjwTK822IU",
  "category": "music"
  # "video": "https://www.youtube.com/watch?v=vKPm8tQ1izo",
  # "thumbnail": "https://i.ytimg.com/vi/aJOTlE1K90k/sddefault.jpg",
}

###
DELETE  http://localhost:4000/video
Content-Type: application/json
Token: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjkzOGYwN2FiMDlmYzBiMjI2ZjYxMSIsImlhdCI6MTYzNDMwNDExNn0.WZAyZs9vA6YBLcva7vaMbuoxOezbduF6nbjfohax4aU


{
  "id": "616d2467e5bee30cf8dd5533"
}

###
DELETE  http://localhost:4000/video/delete-all
Token: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjkzOGYwN2FiMDlmYzBiMjI2ZjYxMSIsImlhdCI6MTYzNDMwNDExNn0.WZAyZs9vA6YBLcva7vaMbuoxOezbduF6nbjfohax4aU
